### ISSUE TITLE
Add NSF GRFP (2016)

### ISSUE THREAD

**Issue by diazrenata** [ogrants/ogrants#177]
---
layout: grant
title: NSF GRFP
author: Renata M. Diaz
ORCID:  0000-0003-0803-4734 
year: 2016
link: https://doi.org/10.6084/m9.figshare.5362636
funder: NSF
program: GRFP
discipline: ecology
status: funded
---

**Comment by ha0ye** [comment]
> ## layout: grant
> title: NSF GRFP
> author: Renata M. Diaz
> ORCID: 0000-0003-0803-4734
> year: 2016
> link: https://doi.org/10.6084/m9.figshare.5362636
> funder: NSF
> program: GRFP
> discipline: ecology
> status: funded
